### ISSUE TITLE
add support for multiple plugins of the same name

### ISSUE THREAD

**Issue by UiP9AV6Y** [helio/puppet-fluentbit#15]
i would like to create the following output pipeline with puppet

```ini
[OUTPUT]
    Name  es
    Match docker.*
    Host  elastic
    Port  9200
    Index docker

[OUTPUT]
    Name  es
    Match system.*
    Host  elastic
    Port  9200
    Index system
```

the **$input_plugins**, **$output_plugins** and **$filters** parameters are hashes with the keys being the plugin names. i would have to create the resources outside of the module in order to support the desired result above.

**Comment by UiP9AV6Y** [comment]
i can create a PR for this but i would like to know how we go about changes to the module API.
ideally the $input_plugins, $output_plugins and $filters would have to be replaced with arrays of a custom type

```puppet
type Fluentbit::Plugin = Struct[{
  name   => String[1],
  params => Hash
}]
```

with that in place, we can iterate through the list and create the resources as needed.

also the $configfile of the plugin defined types should include the $name variable in the default value. e.g.:
```puppet
define fluentbit::output::es(
  String $configfile            = "/etc/td-agent-bit/output_es_${name}.conf",
...
```

**Comment by khaefeli** [comment]
@UiP9AV6Y Thank you very much for your work and sorry for the delayed response. 
I think switching to arrays with a custom type should be fine. I'll test it on our infrastructure and release v0.2 asap to forge.

**Comment by khaefeli** [comment]
merged & released.
